project:
  type: website

website:
  title: "Curiosity Trace"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bdsaglam
      - icon: twitter
        href: https://twitter.com/bdsaglam
  google-analytics: "G-498T1C2SN2"

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


