project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bdsaglam
      - icon: twitter
        href: https://twitter.com/bdsaglam
format:
  html:
    theme: cosmo
    css: styles.css



