project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - slides/**

website:
  title: "Barış Deniz Sağlam"
  site-url: https://barisdeniz.is-a.dev
  search: false
  navbar:
    pinned: false
    background: light
    right:
      - text: Home
        href: index.html
      - text: Writing
        href: writing.html
      - text: Projects
        href: projects.html
      - text: CV
        href: cv.html
  google-analytics: "G-498T1C2SN2"

format:
  html:
    theme: theme.scss
    toc: false
    grid:
      body-width: 720px
    anchor-sections: false
    highlight-style: github

execute:
  freeze: auto
