project:
  type: website
  output-dir: docs

website:
  title: "Curiosity Trace"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bdsaglam
      - icon: twitter
        href: https://twitter.com/bdsaglam
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


